<?php

namespace temple\data\persistence\db\query ;

/**
 * TODOC
 *
 * @author florent
 */
class QueryResult {

	private $rowCount ;

	private $rows ;

	private $generatedId ;

	/**
	 * Constructor.
	 * TODOC
	 * @param number $rowCount
	 * @param array $rows
	 * @param string $lastInsertId
	 */
	public function __construct($rowCount, array $rows = [], $generatedId = 0) {
		$this->rowCount = $rowCount ;
		$this->rows = $rows ;
		$this->generatedId = $generatedId ;
	}

	/**
	 * @return int the count of affected or returned rows by the executed query.
	 */
	public final function getRowCount() {
		return $this->rowCount ;
	}

	/**
	 * @return array an array of associative arrays TODOC
	 */
	public final function getRows() {
		return $this->rows ;
	}

	/**
	 * @return int the id generated by the executed query, 0 if none.
	 */
	public final function getGeneratedId() {
		return $this->generatedId ;
	}

}
